### ISSUE TITLE
Error when building models when .kps indicates mixed path separators

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/lexical-models#21]
The `.kps` seems to have hardcoded paths with backslashes in the `<Files>` section:

```xml
    <File>
      <Name>..\build\example.en.custom.model.js</Name>
      <Description>Lexical model example.en.custom.model.js</Description>
      <CopyLocation>0</CopyLocation>
      <FileType>.model.js</FileType>
    </File>
```

This fails to build on platforms with `/` path separators (e.g., macOS, Linux).

```
Validating model /Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_wahkohtowin/
Building model /Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_wahkohtowin/
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '../source/..\build\example.crk.wordlist_wahkohtowin.model.js'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at /Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_wahkohtowin/build/obj/tools/kmp-compiler.js:104:27
    at Array.forEach (<anonymous>)
    at KmpCompiler.buildKmpFile (/Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_wahkohtowin/build/obj/tools/kmp-compiler.js:103:27)
    at LexicalModelCompiler.compile (/Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_wahkohtowin/build/obj/tools/index.js:141:21)
    at Object.<anonymous> (/Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_wahkohtowin/build/obj/release/example/crk.wordlist_wahkohtowin/source/model.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
Validating model /Users/santoseadmin/Work/lexical-models/release/example/en.custom/
Building model /Users/santoseadmin/Work/lexical-models/release/example/en.custom/
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '../source/..\build\example.en.custom.model.js'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at /Users/santoseadmin/Work/lexical-models/release/example/en.custom/build/obj/tools/kmp-compiler.js:104:27
    at Array.forEach (<anonymous>)
    at KmpCompiler.buildKmpFile (/Users/santoseadmin/Work/lexical-models/release/example/en.custom/build/obj/tools/kmp-compiler.js:103:27)
    at LexicalModelCompiler.compile (/Users/santoseadmin/Work/lexical-models/release/example/en.custom/build/obj/tools/index.js:141:21)
    at Object.<anonymous> (/Users/santoseadmin/Work/lexical-models/release/example/en.custom/build/obj/release/example/en.custom/source/model.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
Validating model /Users/santoseadmin/Work/lexical-models/release/example/en.wordlist/
Building model /Users/santoseadmin/Work/lexical-models/release/example/en.wordlist/
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '../source/..\build\example.en.wordlist.model.js'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at /Users/santoseadmin/Work/lexical-models/release/example/en.wordlist/build/obj/tools/kmp-compiler.js:104:27
    at Array.forEach (<anonymous>)
    at KmpCompiler.buildKmpFile (/Users/santoseadmin/Work/lexical-models/release/example/en.wordlist/build/obj/tools/kmp-compiler.js:103:27)
    at LexicalModelCompiler.compile (/Users/santoseadmin/Work/lexical-models/release/example/en.wordlist/build/obj/tools/index.js:141:21)
    at Object.<anonymous> (/Users/santoseadmin/Work/lexical-models/release/example/en.wordlist/build/obj/release/example/en.wordlist/source/model.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by darcywong00** [comment]
Fixed in #23
